version: "3.8"

services:
  backend:
    build: ./backend
    container_name: student-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql:/studentapp.cjqme0ok6rs1.ap-south-1.rds.amazonaws.com/:3306/studentdb
      SPRING_DATASOURCE_USERNAME: admin
       SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  frontend:
    build: ./frontend
    container_name: student-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always